api: Make error clearer if target/feature does not exist
Before this would just show:

    Error: error decoding response body: expected value at line 1 column 1

    Caused by:
	expected value at line 1 column 1